# NumPy

In [1]:
# This is a list
height = [1.75, 1.45, 1.90, 1.67, 1.68]
height


[1.75, 1.45, 1.9, 1.67, 1.68]

In [2]:
weigth = [70, 30, 80, 65, 60]
weigth

[70, 30, 80, 65, 60]

In [46]:
# python can not make operation on lists then it is necessary to create arrays with numpy

import numpy as np

In [9]:
np_height = np.array(height)
height


[1.75, 1.45, 1.9, 1.67, 1.68]

In [10]:
np_weigth = np.array(weigth)
np_weigth

array([70, 30, 80, 65, 60])

In [13]:
# To calculate the BMI
bmi = np_weigth / np_height ** 2
bmi

array([22.85714286, 14.26872771, 22.16066482, 23.30668005, 21.2585034 ])

You should still pay attention, though. First of all, NumPy can do all of this so easily because it assumes that your NumPy array can only contain values of a single type. It's either an array of floats, either an array of booleans, and so on. If you do try to create an array with different types, like this for example, the resulting NumPy array will contain a single type, string in this case. The boolean and the float were both converted to strings. Second, you should know that a NumPy array is simply a new kind of Python type, like the float, string and list types from before. This means that it comes with its own methods, which can behave differently than you'd expect.

In [16]:
python_list = [1, 2, 3]
python_array = np.array([1, 2, 3])

In [19]:
python_list + python_array

array([2, 4, 6])

In [18]:
python_array + python_array

array([2, 4, 6])

In [20]:
bmi

array([22.85714286, 14.26872771, 22.16066482, 23.30668005, 21.2585034 ])

In [21]:
bmi[1]

14.26872770511296

In [22]:
bmi > 22.3

array([ True, False, False,  True, False])

In [23]:
# to subset
bmi[bmi > 22.3]

array([22.85714286, 23.30668005])

### Your First NumPy Array
You're now going to dive into the world of baseball. Along the way, you'll get comfortable with the basics of numpy, a powerful package to do data science. <br>

A list baseball has already been defined in the Python script, representing the height of some baseball players in centimeters. Can you add some code to create a numpy array 
from it?

### Instructions

Import the`numpy` package as `np`, so that you can refer to `numpy` with `np`.
Use `np.array()` to create a `numpy` array from `baseball`. Name this array np_baseball.
Print out the type of `np_baseball` to check that you got it right.

```python
# Import the numpy package as np


baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Create a numpy array from baseball: np_baseball


# Print out type of np_baseball

```


In [26]:
# Import the numpy package as np
#import numpy as np

baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)




In [27]:
# Print out type of np_baseball
print(type(np_baseball))

<class 'numpy.ndarray'>


### Baseball players' height
You are a huge baseball fan. You decide to call the MLB (Major League Baseball) and ask around for some more statistics on the height of the main players. They pass along data on more than a thousand players, which is stored as a regular Python list: height_in. The height is expressed in inches. Can you make a numpy array out of it and convert the units to meters? <br>

height_in is already available and the numpy package is loaded, so you can start straight away (Source: stat.ucla.edu).

Create a numpy array from `height_in`. Name this new array `np_height_in`. <br>
Print `np_height_in`. <br>
Multiply `np_height_in` with `0.0254` to convert all height measurements from inches to meters. Store the new values in a new array, `np_height_m`.<br>
Print out `np_height_m` and check if the output makes sense.<br>



In [38]:
# Import numpy
import numpy as np

# Create a numpy array from height_in: np_height_in
np_height_in = np.array(height_in)

# Print out np_height_in
print(np_height_in)

# Convert np_height_in to m: np_height_m
np_height_m = np_height_in * 0.0254

# Print np_height_m
print(np_height_m)

[72 65 60 75 68]
[1.8288 1.651  1.524  1.905  1.7272]


In [39]:
np.array([True, 1, 2]) + np.array([3, 4, False])

array([4, 5, 2])

## Subsetting NumPy Arrays<br>
Subsetting (using the square bracket notation on lists or arrays) works exactly the same with both lists and arrays.<br>

This exercise already has two lists, height_in and weight_lb, loaded in the background for you. These contain the height and weight of the MLB players as regular lists. It also has two numpy array lists, np_weight_lb and np_height_in prepared for you.<br>

In [48]:
!pip show numpy

Name: numpy
Version: 1.23.5
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD
Location: /Users/zaidemontesortiz/opt/anaconda3/lib/python3.9/site-packages
Requires: 
Required-by: astropy, biopython, bkcharts, bokeh, Bottleneck, cafeplotter, contourpy, daal4py, datashader, datashape, gensim, GEOparse, h5py, holoviews, hvplot, imagecodecs, imageio, matplotlib, matplotlib-venn, mkl-fft, mkl-random, numba, numexpr, pandas, patsy, periodictable, pyerfa, PyWavelets, scikit-image, scikit-learn, scipy, seaborn, statsmodels, tables, tifffile, xarray


In [1]:
!pip install numpy

In [3]:
!pip install numpy --user

In [4]:
!conda install numpy

done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 23.1.0
  latest version: 24.11.0

Please update conda by running

    $ conda update -n base -c defaults conda

Or to minimize the number of packages updated during conda update use

     conda install conda=24.11.0



# All requested packages already installed.

