# 2D Numpy Arrays

If you ask for the type of these arrays, Python tells you that they are numpy.ndarray. numpy dot tells you it's a type that was defined in the numpy package. ndarray stands for n-dimensional array. The arrays np_height and np_weight are one-dimensional arrays, but it's perfectly possible to create 2 dimensional, three dimensional, heck even seven dimensional arrays! Let's stick to 2 in this video though.

In [1]:
import numpy as np

In [2]:
np_height = np.array([1.75, 1.45, 1.90, 1.67, 1.68])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])

In [3]:
type(np_height)

numpy.ndarray

In [4]:
type(np_weight)

numpy.ndarray

You can create a 2D numpy array from a regular Python list of lists. Let's try to create one numpy array for all height and weight data of your family, like this. If you print out np_2d now, you'll see that it is a rectangular data structure: Each sublist in the list, corresponds to a row in the two dimensional numpy array. From np_2d.shape, you can see that we indeed have 2 rows and 5 columns. shape is a so-called attribute of the np2d array, that can give you more information about what the data structure looks like. Note that the syntax for accessing an attribute looks a bit like calling a method, but they are not the same! Remember that methods have round brackets after them, and, you can see here, attributes do not. Also for 2D arrays, the NumPy rule applies: an array can only contain a single type. If you change one float to be string, all the array elements will be coerced to strings, to end up with a homogeneous array.

In [6]:
np_2d = np.array([[1.75, 1.45, 1.90, 1.67, 1.68],[65.4, 59.2, 63.6, 88.4, 68.7]] )
np_2d

array([[ 1.75,  1.45,  1.9 ,  1.67,  1.68],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

In [7]:
np_2d.shape

(2, 5)

In [9]:
# Subsetting
np_2d[0][2]

1.9

In [10]:
np_2d[0, 2]

1.9

In [11]:
# Second and third value
np_2d[:, 1:3]

array([[ 1.45,  1.9 ],
       [59.2 , 63.6 ]])

In [12]:
#if You want only the second row
np_2d[1,:]

array([65.4, 59.2, 63.6, 88.4, 68.7])

### Your First 2D NumPy Array
Before working on the actual MLB data, let's try to create a 2D numpy array from a small list of lists.

In this exercise, `baseball` is a list of lists. The main list contains 4 elements. Each of these elements is a list containing the height and the weight of 4 baseball players, in this order. `baseball` is already coded for you in the script.

Use `np.array()` to create a 2D `numpy` array from `baseball`. Name it `np_baseball`.
Print out the type of `np_baseball`.
Print out the shape attribute of `np_baseball`. Use `np_baseball.shape`.

```python
import numpy as np

baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Create a 2D numpy array from baseball: np_baseball


# Print out the type of np_baseball


# Print out the shape of np_baseball
```

In [21]:


baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array([[180, 78.4],[215, 102.7],[210, 98.5],[188, 75.2]])


In [22]:
# Print out the type of np_baseball
print(type(np_baseball))


<class 'numpy.ndarray'>


In [23]:
# # Print out the shape of np_baseball
print(np_baseball.shape)

(4, 2)


### Baseball data in 2D form
You realize that it makes more sense to restructure all this information in a 2D `numpy` array.

You have a Python list of lists. In this list of lists, each sublist represents the height and weight of a single baseball player. The name of this list is `baseball` and it has been loaded for you already (although you can't see it).

Store the data as a 2D array to unlock `numpy`'s extra functionality.

### Instructions

Use `np.array()` to create a 2D `numpy` array from `baseball`. Name it np_baseball.
Print out the `shape` attribute of `np_baseball`.

```python
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = 

# Print out the shape of np_baseball

```

In [24]:

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the shape of np_baseball
print(np_baseball.shape)


(4, 2)


Subsetting 2D NumPy Arrays
If your 2D numpy array has a regular structure, i.e. each row and column has a fixed number of values, complicated ways of subsetting become very easy. Have a look at the code below where the elements `"a"` and `"c"` are extracted from a list of lists.

```python
# numpy
import numpy as np
np_x = np.array(x)
np_x[:, 0]
````

The indexes before the comma refer to the rows, while those after the comma refer to the columns. The `:` is for slicing; in this example, it tells Python to include all rows.

### Instructions
Print out the 50th row of `np_baseball`.
Make a new variable, `np_weight_lb`, containing the entire second column of `np_baseball`.
Select the height (first column) of the 124th baseball player in `np_baseball` and print it out.


```python
import numpy as np

np_baseball = np.array(baseball)

# Print out the 50th row of np_baseball


# Select the entire second column of np_baseball: np_weight_lb


# Print out height of 124th player
```

In [30]:
np_baseball = np.array(baseball)
# Print out the 50th row of np_baseball
print(np_baseball[:, 0])

[180. 215. 210. 188.]


In [31]:
print(np_baseball[49, :])

IndexError: index 49 is out of bounds for axis 0 with size 4

In [32]:
print(baseball)

[[180, 78.4], [215, 102.7], [210, 98.5], [188, 75.2]]


In [33]:


np_baseball = np.array(baseball)

# Print out the 50th row of np_baseball
#print(np_baseball[49,:])

# Select the entire second column of np_baseball: np_weight_lb

np_weight_lb = np_baseball[:, 1]


# Print out height of 124th player
print(np_baseball[123, 0])

IndexError: index 49 is out of bounds for axis 0 with size 4